variables:
  DEBIAN_PACKAGE_MANAGERS: >
    cabal-install ghc
    composer
    golang
    npm
    r-base
    ruby
    julia
    maven
  DEBIAN_OTHER_DEPS: >

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq
  - apt-get install -y -qq python3 python3-pip
  - pip3 install --upgrade pip setuptools
  - pip3 install -r requirements.txt -r test-requirements.txt

run_tests:
  image: ubuntu:rolling
  cache:
    paths:
    - ~/.cache/pip
    - vendor/
  script:
  
  - apt-get install -y -qq $DEBIAN_PACKAGE_MANAGERS $DEBIAN_OTHER_DEPS
  # GemRequirementTest requires dummy gem 'ruby' which is not installed
  - gem install ruby
  - py.test
  - codecov

check_code:
  image: ubuntu:rolling
  cache:
    paths:
    - ~/.cache/pip
    - ~/.local/share/coala-bears/
  script:
  - apt-get install -y -qq git
  - pip3 install .
  - pip3 install --pre coala-bears
  - python3 -m nltk.downloader punkt maxent_treebank_pos_tagger averaged_perceptron_tagger
  - coala-ci
