variables:
  DEBIAN_PACKAGE_MANAGERS: >
    cabal-install ghc
    cargo
    composer
    golang
    luarocks
    npm
    r-base
    ruby
    julia
    maven
  DEBIAN_OTHER_DEPS: >
    oracle-java7-installer

cache:
  paths:
    - ~/.local/share/coala-bears/
    - ~/.cache/pip
    - vendor/

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq
  - apt-get install -y -qq python3 python3-pip
  - pip3 install --upgrade pip setuptools
  - pip3 install -r requirements.txt -r test-requirements.txt

run_tests:
  image: ubuntu:rolling
  script:
    - apt-get install -y -qq software-properties-common
    - echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    - add-apt-repository -y ppa:webupd8team/java
    - apt-get update -qq
    - apt-get install -y $DEBIAN_PACKAGE_MANAGERS $DEBIAN_OTHER_DEPS
    - py.test --cov-fail-under=100
    - codecov

check_code:
  image: ubuntu:rolling
  script:
    - apt-get install -y -qq git
    - pip3 install .
    - pip3 install --pre coala-bears
    - coala-ci
