variables:
  DEBIAN_FRONTEND: noninteractive
  DEBIAN_PACKAGE_MANAGERS: >
    cabal-install ghc
    cargo
    composer
    golang
    luarocks
    npm
    python3-pip
    r-base
    ruby
    julia
    maven
  DEBIAN_OTHER_DEPS: >
    oracle-java7-installer

cache:
  paths:
    - ~/.local/share/coala-bears/
    - ~/.cache/pip
    - vendor/

.common_script: &common_script
  - pip3 install --upgrade pip setuptools
  - pip3 install -r requirements.txt -r test-requirements.txt
  - py.test --cov-fail-under=100
  - codecov

run_tests:
  image: ubuntu:rolling
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq software-properties-common
    - echo 'oracle-java7-installer shared/accepted-oracle-license-v1-1
            select true' | /usr/bin/debconf-set-selections
    - add-apt-repository -y ppa:webupd8team/java
    - apt-get update -qq
    - apt-get install -y $DEBIAN_PACKAGE_MANAGERS $DEBIAN_OTHER_DEPS
  script: *common_script

check_code:
  image: ubuntu:rolling
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq python3-pip git
    - pip3 install .
    - pip3 install --pre coala-bears
  script:
    - coala-ci
